# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
tone_instructions: "Provide professional, constructive, and actionable feedback. Focus on code quality, security, and Cairo/Starknet best practices."
early_access: true
enable_free_tier: true

reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  auto_title_placeholder: "@coderabbitai"
  review_status: true
  commit_status: true
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  poem: false
  path_filters:
    # Build outputs and dependencies
    - "!**/target/**"
    - "!**/bin/**"
    - "!**/build/**"
    - "!**/node_modules/**"
    # Version control and configuration
    - "!**/.git/**"
    # Lock files
    - "!**/Scarb.lock"
    - "!**/package-lock.json"
    - "!**/yarn.lock"
  path_instructions:
    - path: "**/*.cairo"
      instructions: |
        Review Cairo smart contract code with focus on:
        - Security vulnerabilities (reentrancy, overflow, access control)
        - Gas optimization and storage efficiency
        - Proper use of Starknet decorators and storage patterns
        - Correct felt252 and type handling
        - Event emission for state changes
        - Proper error handling with assert and custom errors
        - Follow Cairo and Starknet coding conventions
    - path: "**/*.toml"
      instructions: |
        Review Scarb.toml and configuration files for:
        - Correct dependency versions and compatibility
        - Proper project metadata
        - Build configuration correctness
    - path: "**/tests/**"
      instructions: |
        Review test files for:
        - Adequate test coverage for edge cases
        - Proper test isolation
        - Meaningful assertions and error messages
        - Testing both success and failure paths
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "main"

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  learnings:
    scope: "auto"
  issues:
    scope: "auto"
  jira:
    project_keys: []
  linear:
    team_keys: []
  pull_requests:
    scope: "auto"
