#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
usage: capture-replay-rpc-fixtures.sh --rpc-url <url> [--block <number> ...] [--out-dir <path>]

Captures Starknet JSON-RPC fixtures for replay tests:
  - starknet_getBlockWithTxs
  - starknet_getStateUpdate

Examples:
  ./scripts/capture-replay-rpc-fixtures.sh --rpc-url https://starknet-mainnet.public.blastapi.io/rpc/v0_7
  ./scripts/capture-replay-rpc-fixtures.sh --rpc-url https://rpc.example --block 7242623 --block 7242624
EOF
}

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT_DIR/crates/node/tests/fixtures/replay/rpc"
RPC_URL="${STARKNET_RPC_URL:-}"
declare -a BLOCKS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --rpc-url)
      [[ $# -ge 2 ]] || { echo "--rpc-url requires a value" >&2; exit 1; }
      RPC_URL="$2"
      shift 2
      ;;
    --block)
      [[ $# -ge 2 ]] || { echo "--block requires a value" >&2; exit 1; }
      BLOCKS+=("$2")
      shift 2
      ;;
    --out-dir)
      [[ $# -ge 2 ]] || { echo "--out-dir requires a value" >&2; exit 1; }
      OUT_DIR="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$RPC_URL" ]]; then
  echo "missing RPC URL. pass --rpc-url or set STARKNET_RPC_URL." >&2
  exit 1
fi

if [[ ! "$RPC_URL" =~ ^https?:// ]]; then
  echo "RPC URL must use http or https scheme: $RPC_URL" >&2
  exit 1
fi

if [[ ${#BLOCKS[@]} -eq 0 ]]; then
  BLOCKS=(7242623 7242624 7242625)
fi

if ! command -v curl >/dev/null 2>&1; then
  echo "curl is required." >&2
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required." >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

capture_method() {
  local method="$1"
  local block_number="$2"
  local output_path="$3"

  if [[ ! "$block_number" =~ ^[0-9]+$ ]]; then
    echo "invalid block number: $block_number" >&2
    exit 1
  fi

  local response
  response="$(
    curl -sS "$RPC_URL" \
      -H 'content-type: application/json' \
      --data-binary "$(jq -cn \
        --arg method "$method" \
        --argjson block "$block_number" \
        '{jsonrpc:"2.0",id:1,method:$method,params:[{block_number:$block}]}' \
      )"
  )"

  if ! jq -e '.error == null and .result != null' >/dev/null <<<"$response"; then
    echo "rpc request failed for method=$method block=$block_number" >&2
    echo "$response" >&2
    exit 1
  fi

  jq -S '.result' <<<"$response" >"$output_path"
}

for block in "${BLOCKS[@]}"; do
  echo "capturing block $block"
  capture_method \
    "starknet_getBlockWithTxs" \
    "$block" \
    "$OUT_DIR/mainnet_block_${block}_get_block_with_txs.json"
  capture_method \
    "starknet_getStateUpdate" \
    "$block" \
    "$OUT_DIR/mainnet_block_${block}_get_state_update.json"
done

captured_at="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
{
  echo "# Replay RPC Capture Metadata"
  echo
  echo "- Captured at: $captured_at"
  echo "- RPC URL: $RPC_URL"
  echo "- Block numbers: ${BLOCKS[*]}"
  echo
  echo "Generated by \`scripts/capture-replay-rpc-fixtures.sh\`."
} >"$OUT_DIR/CAPTURE_METADATA.md"

PASTIS_FIXTURE_LOCK_UPDATE=1 "$ROOT_DIR/scripts/check-replay-fixture-lock.sh"
echo "capture complete: $OUT_DIR"
