#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export PASTIS_PERF_ITERATIONS="${PASTIS_PERF_ITERATIONS:-3000}"
export PASTIS_BUDGET_DUAL_EXECUTE_P99_US="${PASTIS_BUDGET_DUAL_EXECUTE_P99_US:-5000}"
export PASTIS_BUDGET_NOTIFICATION_DECODE_P99_US="${PASTIS_BUDGET_NOTIFICATION_DECODE_P99_US:-1000}"
export PASTIS_BUDGET_MCP_VALIDATE_P99_US="${PASTIS_BUDGET_MCP_VALIDATE_P99_US:-1000}"
export PASTIS_BUDGET_DUAL_EXECUTE_MIN_OPS_PER_SEC="${PASTIS_BUDGET_DUAL_EXECUTE_MIN_OPS_PER_SEC:-1000}"

(
  cd "${ROOT_DIR}"
  cargo run --locked --release -p starknet-node --bin perf-budget
)
